categories:
  - name: "Magyar"
    sources:
      - name: "Telex"
        url: "telex.hu"
        rss:
          - "https://telex.hu/rss/belfold"
          - "https://telex.hu/rss/defacto"
          - "https://telex.hu/rss/direkt36"
        preference: "Kiemelt prioritás: Választási eredmények, közvélemény-kutatások, új törvények elfogadása, költségvetési és makrogazdasági adatok, miniszteri lemondások. Közepes prioritás: Parlamenti viták, pártok sajtótájékoztatói. Alacsony prioritás (ignoráld): Bűnügyek, balesetek, kis színes hírek, időjárás. KIVÉTEL: Csak akkor vegyél figyelembe bűnügyet, ha az kormányválságot okoz vagy súlyos korrupciót tár fel."
        filter:
          - "belfold"
          - "defacto"
          - "direkt36"
        language: "Hungarian"


      - name: "Index"
        url: "index.hu"
        rss:
          - "https://index.hu/belfold/rss/"
        preference: "Fókuszálj a 'Hard News' kategóriára: Törvényhozás, adóváltozások, sztrájkok, kritikus infrastruktúra leállása, diplomáciai konfliktusok. Csak azokat a híreket emeld ki, amelyek közvetlen hatással vannak az ország működésére vagy a gazdaságra. Kezeld alacsony prioritásként a hatásvadász címeket, ahol a tartalom csak spekuláció. A rendőrségi és tűzoltósági híreket (kék hírek) teljesen hagyd figyelmen kívül, kivéve terrorveszély esetén."
        language: "Hungarian"
        filter:
          - "belfold"

      - name: "Válasz Online"
        url: "valaszonline.hu"
        rss:
          - "https://www.valaszonline.hu/feed/"
        preference: "Legmagasabb prioritás: Átfogó elemzések az oktatás, egészségügy vagy demográfia helyzetéről, választókerületi esélylatolgatások adatokkal alátámasztva, mélyinterjúk döntéshozókkal. Alacsony prioritás: Rövidhírek, kulturális ajánlók, egyéni sorsokat bemutató riportok, amennyiben nem világítanak rá rendszerszintű hibákra."
        language: "Hungarian"

      - name: "Mandiner"
        url: "mandiner.hu"
        rss:
          - "https://mandiner.hu/publicapi/hu/rss/mandiner/articles"
        preference: "Keresd a stratégiai tartalmat: A miniszterelnök és a kormánytagok iránymutató beszédei, a kormány hivatalos álláspontja EU-s vitákban, választási stratégia ismertetése. Hagyd figyelmen kívül az ellenzéki politikusok gúnyolását, a provokatív szemlézéseket és a napi politikai adok-kapokot. Csak az ideológiai és stratégiai elemzések érdekelnek."
        language: "Hungarian"
        filter:
          - "belfold"

      - name: "24.hu"
        url: "24.hu"
        rss:
          - "https://24.hu/belfold/feed/"
        preference: "Szigorú szűrés: Kizárólag akkor emeld ki a cikket, ha az oknyomozó újságírás eredménye (korrupció, visszaélés feltárása), választási csalásról szól, vagy jelentős gazdasági bejelentést tartalmaz. Minden más téma (baleset, celeb, napi daráló, véleménycikk) alacsony prioritású. A rendőrségi rovat hírei tiltólistásak."
        language: "Hungarian"
        filter:
          - "belfold"


  - name: "Gazdaság"
    sources:
      - name: "Financial Times"
        url: "ft.com"
        rss:
          - "https://www.ft.com/rss/home"
        preference: "High Priority: EU regulatory changes (antitrust, AI act, Green Deal), Defense sector funding and contracts, Tech sector earnings of major players, Central Bank rate decisions (ECB/Fed). Medium Priority: General market summaries. Low Priority (Ignore): Lifestyle, Arts, Opinion pieces by non-economists. Goal: Identify volatility triggers for an EU-based investor."
        language: "English"

      - name: "Reuters Business"
        url: "reuters.com"
        rss:
          - "https://feeds.reuters.com/reuters/businessNews"
        preference: "Top Priority Triggers: Mergers & Acquisitions deals in Tech/Defense, Supply chain disruptions (semiconductors, energy), Inflation data releases, sudden currency fluctuations (EUR/USD). Downrank: 'Analysis' pieces that merely summarize past events without forward-looking value. Strictly factual, market-moving news only."
        language: "English"

      - name: "The Economist"
        url: "economist.com"
        rss:
          - "https://www.economist.com/leaders/rss.xml"
          - "https://www.economist.com/briefing/rss.xml"
          - "https://www.economist.com/international/rss.xml"
          - "https://www.economist.com/finance-and-economics/rss.xml"
        preference: "High Priority: Articles discussing long-term shifts in Global Trade (de-globalization), Geopolitical impacts on supply chains, and major elections in G20 countries. Focus on the 'Leaders' and 'Briefing' sections. Ignore: Book reviews, localized cultural stories, and minor country politics unless it affects the global economy."
        language: "English"


  - name: "Geopolitika"
    sources:
      - name: "AP News"
        url: "apnews.com"
        rss:
          - "https://openrss.org/apnews.com"
        preference: "Critical Importance: Declaration of war, signing of peace treaties or alliances, coup d'états, results of national elections in major powers, natural disasters with global infrastructure impact. Low Importance: Local crime stories anywhere in the world, human interest stories, minor diplomatic spats. Focus strictly on border-altering or regime-changing events."
        language: "English"

      - name: "Al Jazeera English"
        url: "aljazeera.com"
        rss:
          - "https://www.aljazeera.com/xml/rss/all.xml"
        preference: "High Priority: Conflicts in the Middle East and Global South involving major powers, resource wars (oil, lithium, water), significant protests threatening regime stability. Low Priority: Sports, localized community news, op-eds without factual basis. Goal: Understand non-Western perspectives on major global conflicts."
        language: "English"